builds:
  - main: ./cmd/gocask
    id: "server"
    binary: gocask
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

  - main: ./cmd/gccli
    id: "cli"
    binary: gccli
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
