// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Time is an autogenerated mock type for the Time type
type Time struct {
	mock.Mock
}

// NowUnix provides a mock function with given fields:
func (_m *Time) NowUnix() uint32 {
	ret := _m.Called()

	var r0 uint32
	if rf, ok := ret.Get(0).(func() uint32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint32)
	}

	return r0
}

type mockConstructorTestingTNewTime interface {
	mock.TestingT
	Cleanup(func())
}

// NewTime creates a new instance of Time. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTime(t mockConstructorTestingTNewTime) *Time {
	mock := &Time{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
